name: build 23.05 for meraki mr32
on:
  workflow_dispatch:
  workflow_call:

jobs:
  call-image-builder-meraki-mr32-23_05:
    permissions:
      contents: write
    uses:
      ./.github/workflows/_image_builder.yml
    with:
      build_settings: 
        '{"SOURCE_REPO":  "https://github.com/openwrt/openwrt.git", 
        "SOURCE_BRANCH": "openwrt-23.05",
        "BUILD_REPO":    "https://github.com/${{github.repository}}.git",
        "BUILD_BRANCH": "23.05-mr32",
        "BUILD_INIT": "init_build.sh",
        "BUILD_TYPE":  "mr32",
        "BUILD_VER": "23.05-SNAPSHOT",
        "BUILD_TAG": "",
        "BUILD_SYNC": "n",
        "BUILD_KMOD": "y",
        "BUILD_DEVICE": "MR32"}'
